[metadata]
name = django-casdoor-auth
version = 0.0.0
author = Casdoor
author_email = admin@casdoor.org
url = https://github.com/casdoor/django-casdoor-auth
description = Django app for signing in with Casdoor
long_description = file: README.md
long_description_content_type = text/markdown
license = Apache 2.0
platform = any
keywords = Casdoor, Django, SSO, OAuth
classifiers =
	Intended Audience :: Developers
	License :: OSI Approved :: Apache Software License
	Operating System :: OS Independent
	Programming Language :: Python
	Programming Language :: Python :: 3
	Programming Language :: Python :: 3.10
	Programming Language :: Python :: 3.11
	Programming Language :: Python :: 3.12
	Programming Language :: Python :: 3.13
	Programming Language :: Python :: 3.14
	Framework :: Django
	Framework :: Django :: 4.2
	Framework :: Django :: 5.2
	Framework :: Django :: 6.0

[options]
packages = find:
install_requires =
	django>=4.2
	casdoor>=1.42.0
	PyJWT>=2.0.0
python_requires = >=3.10

[options.packages.find]
exclude =
	tests
	tests.*

[bdist_wheel]
universal = true

[sdist]
formats = gztar
